### ISSUE TITLE
autoNext = false 且文件行数过多时报错

### ISSUE THREAD

**Issue by sjfkai** [leizongmin/node-lei-stream#1]
`autoNext: false` 文件行数为 `20000+`

```
RangeError: Maximum call stack size exceeded
    at new TickObject (node.js:482:24)
    at process.nextTick (node.js:500:26)
    at ReadLineStream.next (C:\Git\programming-pearls\chapter1\node_modules\lei-stream\lib\readline.js:74:13)
    at ReadLineStream.<anonymous> (C:\Git\programming-pearls\chapter1\index.js:31:10)
    at emitOne (events.js:77:13)
    at ReadLineStream.emit (events.js:169:7)
    at ReadLineStream.next (C:\Git\programming-pearls\chapter1\node_modules\lei-stream\lib\readline.js:107:8)
    at ReadLineStream.<anonymous> (C:\Git\programming-pearls\chapter1\index.js:31:10)
    at emitOne (events.js:77:13)
    at ReadLineStream.emit (events.js:169:7)
```

暂时的解决方法:

```
// 读取到一行数据时触发data事件 
s.on('data', function (line) {
    console.log(line);
    process.nextTick(function () {
        s.next();
    });
});
```

**Comment by sjfkai** [comment]
文件内为7位纯数字一行时，20,000行左右就会报错。但我将`test/file/json_big.txt`复制到了200,000行也并没有报错。目前搞不懂是为什么。

**Comment by leizongmin** [comment]
原因可能是你每一行的数据太小，因为读取文件时是一次性读取一块（一般为64KB）的，然后`lei-stream`会一行一行地执行回调，结果嵌套太深导致堆栈溢出，但是到底要嵌套多少层才会导致溢出是与你回调函数的大小有关的。

你提交的Pull Request中，使用`process.nextTick()`即可解决问题，但是`process.nextTick()`会影响读取速度，应尽量避免，所以我又修改了一下程序：https://github.com/leizongmin/node-lei-stream/commit/e43b7f3a325aed7828a0cceb0cbf1ee05aa0b165

目前已发布`lei-stream@1.0.5`，已有的单元测试全部通过。感谢你的支持！
